//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by preferences_page.rc

#define IDD_FOODOCK_PREFERENCES				100
#define IDC_RADIO_LOOKSTYLE_ALIEN			1001
#define IDC_RADIO_LOOKSTYLE_ALBUM			1002
#define IDC_RADIO_LOOKSTYLE_VISUAL			1003
#define IDC_RADIO_MOUSE_SCROLL_DOWN_NEXT	1012
#define IDC_RADIO_MOUSE_SCROLL_DOWN_PREV	1013
#define IDC_EDITBOX_NOW_PLAYING_FORMAT		1023
#define IDC_EDITBOX_COPY_TITLE_FORMAT		1034
#define IDC_CHECKBOX_SHOW_BALLOON			1043
#define IDC_TEXT_COMBOBOX_BALLOON_FORMAT	1045
#define IDC_COMBOBOX_BALLOON_FORMAT			1046
#define IDC_CHECKBOX_DROPPED_FOLDER_CREATE	1063
#define IDC_CHECKBOX_DROPPED_FOLDER_ADD		1064
#define IDC_CHECKBOX_DROPPED_FOLDER_ASK		1065
#define IDC_CHECKBOX_AUTOSAVE_PLAYLIST		1075
#define IDC_CHECKBOX_PLAYLIST_BACKUP		1077
#define IDC_CHECKBOX_SHOW_PREFERENCES_OPT	1086


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
